version: '3'
services:
    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        ports:
          - 9092:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 172.16.42.208
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        ports:
          - 9093:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 172.16.42.208
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        ports:
          - 9094:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 172.16.42.208
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: moose
