version: '3'
services:
    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        ports:
          - 9092:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 172.16.42.208
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: moose
