server.port: 8000
spring.application.name: moose-eureka-server

security:
  basic.enabled: true
  user:
    name: eureka
    password: eureka

eureka:
  instance.hostname: localhost
  server.peer-eureka-nodes-update-interval-ms: 60000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url.defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
