server.port: 8888
spring:
  application.name: moose-config-server
  cloud:
    config.server.git:
      uri: https://gitee.com/yfyi/moose-config-resposity
      searchPaths: moose-config
      username: username
      password: password
    bus.trace.enabled: true
    stream.kafka.binder:
      brokers: localhost:9092,localhost:9093,localhost:9094
      zkNodes: localhost:2181,localhost:2182,localhost:2183/kafka
eureka.client.serviceUrl.defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
management.security.enabled: false