version: '3'
services:
    eureka1:
        image: moose/eureka
        build: .
        container_name: eureka1
        ports:
          - 8001:8000
        environment:
          EUREKA_INSTANCE_HOSTNAME: eureka1
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka2:8000/eureka
          #EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
          #EUREKA_CLIENT_FETCH_REGISTER: "true"

    eureka2:
        image: moose/eureka
        build: .
        container_name: eureka2
        ports:
          - 8002:8000
        environment:
          EUREKA_INSTANCE_HOSTNAME: eureka2
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka1:8000/eureka
          #EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
          #EUREKA_CLIENT_FETCH_REGISTER: "true"

networks:
  default:
    external:
      name: moose
