version: '3'
services:
    client1:
        image: moose/config-client
        build: .
        container_name: client1
        ports:
          - 8881:8881
        environment:
          KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
          ZOOKEEPER_NODES: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka1:8000/eureka,http://eureka2:8000/eureka,http://eureka3:8000/eureka

    client2:
        image: moose/config-client
        build: .
        container_name: client2
        ports:
          - 8882:8881
        environment:
          KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
          ZOOKEEPER_NODES: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka1:8000/eureka,http://eureka2:8000/eureka,http://eureka3:8000/eureka

networks:
  default:
    external:
      name: moose
